<?php 
    $status= $this->formText('status','',array('class'=>'txtmedium'));
    $amount= $this->formText('amount','',array('class'=>'txtmedium'));
    $data= $this->formText('data','',array('class'=>'txtmedium'));
    $paymentinfo= $this->formText('paymentinfo','',array('class'=>'txtmedium'));
    $message= $this->formText('message','',array('class'=>'txtmedium'));
    $security= $this->formText('security','',array('class'=>'txtmedium'));
    $payment= $this->formText('payment','',array('class'=>'txtmedium'));
    $user_id = $this->formSelect('user_id',array('class'=>'slect'));
    $linkindex = $this->baseURL($this->currentController.  '/index');
    $linkadd = $this->baseURL($this->currentController.  '/add');
if(count($this->messageError)>0){
    $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
}

?>
<div class="title">
    <h1 class="titleh1">Thêm Dữ Liệu</h1>
</div>
<form name="appForm" method="post" action="">
                      
                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
                                <div id="row">
                                    <div class="label">NameUser</div>
                                    <div>
                                        <?php echo $user_id;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Status</div>
                                    <div>
                                        <?php echo $status;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>
								<div id="row">
                                    <div class="label">amount</div>
                                    <div>
                                        <?php echo $amount;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>                               
                                <div id="row">
                                    <div class="label">paymentinfo</div>
                                    <?php echo $paymentinfo;?>			
                                </div>
                                <div id="row">
                                    <div class="label">Data</div>
                                    <?php echo $data;?>			
                                </div>
                                <div id="row">
                                    <div class="label">payment</div>
                                    <?php echo $payment;?>			
                                </div>
                                <div class="clr"></div> 
                                <div id="row">
                                    <div class="label">Message</div>
                                    <?php echo $message;?>			
                                </div>
                                <div id="row">
                                    <div class="label">Security</div>
                                    <?php echo $security;?>			
                                </div>
                                <div class="button">
                                    <button type="submit" class="btn btn-success">Save</button></a>
                                    <a href="<?php echo $linkindex?>"><button type="button" class="btn btn-danger">Cancer</button></a>
                                </div>             
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        
                 
                        <!-- END: 	CONTENT -->
</form>