<?php 
	$group_name 	= $this->Item['email'];
    $avatar 		= $this->Item['comment'];
    $linkindex = $this->baseURL($this->currentController.  '/index');
?>
<div class="title">
    <h1 class="titleh1">Xóa Dữ Liệu</h1>
</div>
<form name="appForm" method="post" action="">
                        <div class="clr"></div>
  
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div id="errors">
                             	Ban co chac chacn muon xoa phan tu nay hay khong?
                             </div>                           
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>