<?php 
    $comment= $this->formText('comment',$this->Items['comment'],array('style'=>'width: 250px;height: 
        30px;border-radius: 8px;margin-left: 25px;
        border: 1px solid;margin-top: 2px;'));
    $email = $this->formText('email',$this->Items['email'],array('style'=>'

        width: 250px;
        height: 30px;
        border-radius: 8px;
        margin-left: 25px;
        border: 1px solid;margin-top: 2px;
    '));
    $linkindex = $this->baseURL($this->currentController.  '/index');
    $linkadd = $this->baseURL($this->currentController.  '/add');
if(count($this->messageError)>0){
    $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
}

?>
<div class="title">
    <h1 class="titleh1">Thêm Dữ Liệu</h1>
</div>
<form name="appForm" method="post" action="">
                      
                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div id="row">
                                    <div class="label">Email</div>
                                    <div>
                                        <?php echo $email;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div> 
                                <div id="row">
                                    <div class="label">Comment</div>
                                    <div>
                                        <?php echo $comment;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>                                
                                 
                                <div class="button">
                                    <button type="submit" class="btn btn-success">Save</button></a>
                                    <a href="<?php echo $linkindex?>"><button type="button" class="btn btn-danger">Cancer</button></a>
                                </div>             
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        
                 
                        <!-- END: 	CONTENT -->
</form>