
<?php
    $linkedit = $this->baseURL($this->currentController.  '/edit/id/');
    $linkdelete = $this->baseURL($this->currentController.  '/delete/id/');
    $linkadd = $this->baseURL($this->currentController.  '/add');
   
?>

<div class="layout">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">

                </div>     
            </div>
            <div class="col-md-12">
                <div class="card shadow ">
                    <div class="card-body">
                        <div class="table-responsive">
                            <div class="col-md-12 content1">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h3>Dữ Liệu Xuất Ra <br /></h3>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="<?php echo $linkadd ?>" class="btn btn-danger">Thêm Mới</a>
                                    </div>
                                </div>
                                
                            </div>
                            
                            <table class="table table-bordered" id="dataTable"  cellspacing="0">
                                <thead>
                                        <tr>
                                                <th>Email</th>
                                                <th>Comment</th>
                                                <th>Sửa</th>
                                                <th>Xóa</th>      
                                        </tr>
                                </thead>
                                <?php foreach ($this->Items as $index): ?>
                                <tbody>
                                    <td><?php echo $this->escape($index->email) ?></td>
                                    <td><?php echo $this->escape($index->comment) ?></td>
                                    <td>
                                        <a href="<?php echo $linkedit .$this->escape($index->id) ?>">Sửa</a>

                                    </td>
                                    <td>
                                        <a href="<?php echo $linkdelete .$this->escape($index->id)?>">Xóa</a>
                                    </td>                     
                                </tbody>
                                <?php endforeach ?>
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
                
        </div>
    </div>
</div>

 
