<?php
function truncateString($str, $maxChars = 40, $holder = "...")
{
    if (strlen($str) > $maxChars) {
        return trim(substr($str, 0, $maxChars)) . $holder;
    } else {
        return $str;
    }
}
function Sale($price,$discount)
{
    $sale= $price - $price*($discount/100);
    echo $sale;
}

$linkprbycate = $this->baseURL($this->currentController.'/prbycate/id/');
$linkdetailpr = $this->baseURL($this->currentController.'/detailpr/id/');
?>
<div class="layoutdefault">
   <div class="container">
      <div class="row">
          <div class="col-md-12">
              <div class="row">
                    <div class="col-md-4">

                        <?php foreach ($this->Items as $index): ?>
                            <ul class="list-group">
                               <a class="title1" href=" <?php echo $linkprbycate . $index['id'] ?>"><li class="list-group-item">
                                   <?php echo $index['name'] ?>
                                </li></a> 
                            </ul> 
                        <?php endforeach ?>                     
                    </div>            
                    <div class="col-md-8">
                        <div class="banner">
                            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                    <img class="d-block w-100" style="height: 400px;" src="<?php echo IMAGE_LINK?>/default/system/images/banner.png" alt="First slide">
                                    </div>
                                    <div class="carousel-item">
                                    <img class="d-block w-100" style="height: 400px;" src="<?php echo IMAGE_LINK?>/default/system/images/banner4.png" alt="Second slide">
                                    </div>
                                    <div class="carousel-item">
                                    <img class="d-block w-100" style="height: 400px;" src="<?php echo IMAGE_LINK?>/default/system/images/banner7.png" alt="Third slide">
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                    </div>
              </div>
          </div>
      </div>
   </div>
</div>
<div class="productnew">
    <div class="container">
        <div class="col-md-12">
            <div class="titlepronew">
                <h1>Sản Phẩm Mới Nhất</h1>
            </div>
        </div>
        <div class="col-md-12">
            <div class="listproductnew">
                    <div class="row">
                        <?php foreach ($this->News as $new){ ?>
                            <div class="col-md-3">
                                <div class="course">
                                    <div class="card" style="width: 16rem;">
                                        <div class="card-img" style="height: 150px">
                                              <img class="card-img-top load" style="width: 150px!important;margin-left:55px!important;" src="<?php echo IMAGE_LINK?>/default/system/images/<?php echo $new['image_list']   ?>" alt="Card image cap">
                                        </div>
                                        <div class="card-body">
                                            <h5 class="card-title"><?php echo $new['name'] ?></h5>
                                            <p class="card-text ct"><?php echo truncateString($new['content' ] )?> <a
                                                        href="<?php echo $linkdetailpr .  $new['id']  ?>"> Đọc Tiếp</a></p>
                                            <div class="info">
                                               <span class="card-text pri"><?php echo  number_format($new['price' ]).'đ'; ?>
                                               </span>
                                               <span class="badge badge-secondary"><?php echo $new['discount' ] .'%' ?></span>

                                            </div>

                                            <a href="#" class="btn btn-danger buy">Đặt hàng</a>
                                           <a href="<?php echo $linkdetailpr .  $new['id']  ?>" class="btn btn-primary more">Xem thêm</a>
                                           </div>
                                    </div>
                                </div>
                            </div>
                        <?php  } ?>
                        	
                    </div>          
                </div>
            </div>    
        </div>
        <div class="col-md-12">
            <div class="col-md-3 offset-5">
                <button class="btn-primary select-all">Xem Tất Cả</button>
            </div>           
        </div>     
    </div>
</div>
<div class="producthl">
    <div class="container">
        <div class="col-md-12">
            <div class="titlepronew">
                <h1>Sản Phẩm Nổi Bật</h1>
            </div>
        </div>
        <div class="col-md-12">
            <div class="listproductnew">

                <div class="row">
                    <?php foreach ($this->hightlight as $hl){ ?>
                        <div class="col-md-3">
                            <div class="course">
                                <div class="card" style="width: 16rem;">
                                    <div class="card-img" style="height: 150px">
                                        <img class="card-img-top load " style="width: 150px!important;margin-left:55px!important;" src="<?php echo IMAGE_LINK?>/default/system/images/<?php echo $new['image_list']   ?>"
                                             alt="Card image cap">
                                    </div>

                                    <div class="card-body">
                                        <h5 class="card-title"><?php echo $hl['name'] ?></h5>
                                        <p class="card-text ct"><?php echo truncateString($hl['content' ] )?> <a
                                                    href="<?php echo $linkdetailpr .  $hl['id']  ?>"> Đọc Tiếp</a></p>
                                        <div class="info">
                                               <span class="card-text pri"><?php echo  number_format($hl['price' ]).'đ'; ?>
                                               </span>
                                            <span class="badge badge-secondary"><?php echo $hl['discount' ] .'%' ?></span>

                                        </div>

                                        <a href="#" class="btn btn-danger buy">Đặt hàng</a>
                                        <a href="<?php echo $linkdetailpr .  $hl['id']  ?>" class="btn btn-primary more">Xem thêm</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php  } ?>

                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-3 offset-5">
                <button class="btn-primary select-all">Xem Tất Cả</button>
            </div>           
        </div>     
    </div>
</div>