<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Test</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/user/index' ?>">User <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/category/index' ?>">Category <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/product/index' ?>">Product<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/guestbook/index' ?>">Guestbook<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/transition/index' ?>">Transition<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/order/index' ?>">Order<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item " style="margin-left: 500px">
                    <a class="nav-link" href="<?php echo $this->baseUrl().'/admin/auth2/login' ?>">Đăng Xuất<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>