
<div class="login">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-3">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title">
                            <h3>Login Admin</h3>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <form action="" method="post">
                            <div class="container">
                                <label for="uname"><b>Email</b></label>
                                <input type="text" name="email" id="email">

                                <label for="psw"><b>Password</b></label>
                                <input type="text" name="password" id="password">

                                <?php echo $this->formSubmit('submit','Đăng Nhập');?>
                            </div>
                        </form>
                    </div>
                </div>


            </div>
        </div>

    </div>
</div>


