<?php 
    $name = $this->formText('name',$this->Items['name'],array('class'=>'txtmedium'));
    $DescriptionCategory= $this->formText('description',$this->Items['description'],array('class'=>'txtmedium'));
    $linkindex = $this->baseURL($this->currentController.  '/index');
    $linkadd = $this->baseURL($this->currentController.  '/add');
?>
<div class="title">
    <h1 class="titleh1">Sửa Dữ Liệu</h1>
</div>
<form name="appForm" method="post" action="">
                      
                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div id="row">
                                    <div class="label">Name Category</div>
                                    <?php echo $name;?>
                                </div>
                                <div class="clr"></div>                               
                                <div id="row">
                                    <div class="label">Description</div>
                                    <?php echo $DescriptionCategory;?>
                                </div>
                                <div class="clr"></div>    
                                
                                <div class="button" style="margin-top: 20px">
                                    <button type="submit" class="btn btn-success">Save</button></a>
                                    <a href="<?php echo $linkindex?>"><button type="button" class="btn btn-danger">Cancer</button></a>
                                </div>             
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        
                 
                        <!-- END: 	CONTENT -->
</form>