
<?php
    $linkedit = $this->baseURL($this->currentController.  '/edit/id/');
    $linkdelete = $this->baseURL($this->currentController.  '/delete/id/');
    $linkadd = $this->baseURL($this->currentController.  '/add');
   
?>

<div class="container">
    <div class="row">
        <div class="card shadow md-12">
            <div class="card-body">
                <div class="table-responsive">
                    <div class="col-md-12" style="margin-top: 10px;">
                        <div class="col-md-3">
                            <h3>Dữ Liệu Xuất Ra <br /></h3>
                        </div>
                        <div class="col-md-1 offset-8">
                            <a href="<?php echo $linkadd ?>" style="margin-top: -45px" class="btn btn-danger">Thêm Mới</a>
                        </div>
                    </div>

                    <table class="table table-bordered" id="dataTable"  cellspacing="0">
                        <thead>
                                <tr>
                                        <th>ID</th>
                                        <th>NameCategory</th>
                                        <th>DescriptionCategory</th>
                                        <th>Sửa</th>
                                        <th>Xóa</th>      
                                </tr>
                        </thead>
                        <?php foreach ($this->cateindex as $index): ?>
                        <tbody>
                            <td><?php echo $index['id'] ?></td>
                            <td><?php echo $index['name'] ?></td>
                            <td><?php echo $index['description'] ?></td>
                            <td>
                                <a href="<?php echo $linkedit .$this->escape($index->id) ?>">Sửa</a>
                            </td>
                            <td>
                                <a href="<?php echo $linkdelete .$this->escape($index->id)?>">Xóa</a>
                            </td>                     
                        </tbody>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>
        </div>      
    </div>
</div>

 
