<?php
$name = $this->formText('name',$this->Items['name'],array('class'=>'txtmedium'));
$parent_id = $this->formText('parent_id',$this->Items['parent_id'],array('class'=>'txtmedium'));
$sort_order = $this->formText('sort_order',$this->Items['sort_order'],array('class'=>'txtmedium'));
?>
<form name="appForm" method="post" action="">

                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						      <div id="adminfieldset">
                              <div class="adminheader">Item Detail</div>

                              <div id="row">
                                <div class="label">Name Category</div>
                                <?php echo $name;?>
                              </div>
                              <div class="clr"></div>
                              <div id="row">
                                <div class="label">Parent_ID</div>
                                <?php echo $parent_id;?>
                              </div>
                              <div class="label">Order_Sort</div>
                              <?php echo $sort_order;?>
                              </div>
                                <div class="clr"></div>
                                
                                
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>