<?php 
    $image_list = $this->formFile('image_list','',array('style'=>'width:250px,margin-left: 18px;'));
    $name = $this->formText('name','',array('class'=>'txtmedium'));
    $price = $this->formText('price','',array('class'=>'txtmedium'));
    $discount = $this->formText('discount','',array('class'=>'txtmedium'));
    $brand=$this->formText('brand','',array('class'=>'txtmedium'));
    $linkindex = $this->baseURL($this->currentController.  '/index');
    $linkadd = $this->baseURL($this->currentController.  '/add');
		
if(count($this->messageError)>0){
    $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
}
    
?>
<div class="title">
    <h1 class="titleh1">Thêm Dữ Liệu</h1>
</div>
<form name="appForm" method="post" action="">
                      
                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
								
								<div id="row">
                                    <div class="label">NameCategory</div>
                                    <div>
                                        <select name="category_id" style="margin-left: 25px;border-radius: 8px;height: 32px;width: 247px;">\
                                            <?php foreach ($this->category as $pi): ?>
                                                <option  id="hahaha" name="hahaha"
                                                value="<?php echo $pi['id']; ?>">
                                                    <?php echo $pi['name']; ?></option>
                                            <?php endforeach ?>
                                        </select>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>                               
                                <div id="row">
                                    <div class="label">NameProduct</div>
                                    <?php echo $name;?>			
                                </div>
                                <div id="row">
                                    <div class="label">Price</div>
                                    <?php echo $price;?>			
                                </div>
                                <div id="row">
                                    <div class="label">Discount</div>
                                    <div>
                                       <?php echo $discount;?>
                                    </div>
                                 <div class="clr"></div>
                                 </div>
                                <div id="row">
                                   <div class="label">Brand</div>
                                   <?php echo $brand;?>
                                </div>
                                <div class="clr"></div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Content</div>
                                </div>
                                <div id="row">
                                    <div>
                                         <textarea name="content" id="content" style="margin-top: 40px;">
                                         </textarea>
                                         <script>CKEDITOR.replace('content');</script>
                                    </div>
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">Skill</div>
                                </div>
                                <div id="row">
                                    <div>
                                         <textarea name="skill" id="skill" style="margin-top: 40px;">
                                             </textarea>
                                         <script>CKEDITOR.replace('skill');</script>
                                    </div>
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                   <div class="label">ParameterPro</div>
                                </div>
                                <div id="row">
                                    <div>
                                         <textarea name="ParameterPro" id="ParameterPro" style="margin-top: 40px;">
                                         </textarea>
                                         <script>CKEDITOR.replace('ParameterPro');</script>
                                   </div>
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label"> Image</div>
                                    <?php echo $image_list;?>
                                </div>
                                <div class="button">
                                    <a type="submit" id="submit" name="submit" href=""></a><button  class="btn btn-success">Save</button></a>
                                    <a href="<?php echo $linkindex?>"><button type="button" class="btn btn-danger">Cancer</button></a>
                                </div>
                            <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        
                 
                        <!-- END: 	CONTENT -->
</form>