
<?php
    $linkedit = $this->baseURL($this->currentController.  '/edit/id/');
    $linkdelete = $this->baseURL($this->currentController.  '/delete/id/');
    $linkadd = $this->baseURL($this->currentController.  '/add');
   
?>

<div class="layout">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                </div>     
            </div>
            <div class="col-md-12">
                <div class="card shadow ">
                    <div class="card-body">
                        <div class="table-responsive">
                            <div class="col-md-12 content1">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h3>Dữ Liệu Xuất Ra <br /></h3>
                                    </div>
                                    <div class="col-md-4">
                                        <a href="<?php echo $linkadd ?>" class="btn btn-danger">Thêm Mới</a>
                                    </div>
                                </div>
                                
                            </div>
                            
                            <table class="table table-bordered" id="dataTable"  cellspacing="0">
                                <thead>
                                        <tr>
                                                <th>Category_id</th>
                                                <th>Name</th>
                                                <th>Price</th>
                                                <th>Brand</th>
                                                <th>Discount</th>
                                                <th>Content</th>
                                                <th>Image_List</th>
                                                <th>Sửa</th>
                                                <th>Xóa</th>      
                                        </tr>
                                </thead>
                                <?php foreach ($this->proindex as $pi): ?>
                                <tbody>
                                    <td><?php echo $pi['category_id'] ?></td>
                                    <td><?php echo $pi['name'] ?></td>
                                    <td><?php echo $pi['price']  ?></td>
                                    <td><?php echo $pi['brand']  ?></td>
                                    <td><?php echo $pi['discount']  ?></td>
                                    <td><?php echo $pi['content']  ?></td>
                                    <td><img style="width: 40px" src="<?php echo IMAGE_LINK?>/default/system/images/<?php echo $pi['image_list'] ?>"></td>
                                    <td>
                                        <a href="<?php echo $linkedit .$pi['id']  ?>">Sửa</a>

                                    </td>
                                    <td>
                                        <a href="<?php echo $linkdelete .$pi['id'] ?>">Xóa</a>
                                    </td>                     
                                </tbody>
                                <?php endforeach ?>
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
                
        </div>
    </div>
</div>

 
