<?php 
    $qty= $this->formText('qty',$this->Items['qty'],array('class'=>'txtmedium'));
    $amount= $this->formText('amount',$this->Items['amount'],array('class'=>'txtmedium'));
    $data= $this->formText('data',$this->Items['data'],array('class'=>'txtmedium'));
    $status= $this->formText('status',$this->Items['status'],array('class'=>'txtmedium'));
    $transition_id = $this->formSelect('transition_id',array('class'=>'slect'));
    $product_id = $this->formSelect('product_id',array('class'=>'slect'));
    $linkindex = $this->baseURL($this->currentController.  '/index');
    $linkadd = $this->baseURL($this->currentController.  '/add');
if(count($this->messageError)>0){
    $errors = $this->formErrors($this->messageError,array('id'=>'errors'));
}

?>
<div class="title">
    <h1 class="titleh1">Thêm Dữ Liệu</h1>
</div>
<form name="appForm" method="post" action="">
                      
                        <div class="clr"></div>

                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
						<div id="adminfieldset">
                             <div class="adminheader">Detail</div>
                                <div id="row">
                                    <div class="label">NameTransition</div>
                                    <div>
                                        <?php echo $transition_id;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>
                                <div id="row">
                                    <div class="label">NameProduct</div>
                                    <div>
                                        <?php echo $transition_id;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>
								<div id="row">
                                    <div class="label">Qty</div>
                                    <div>
                                        <?php echo $qty;?>
                                    </div>
                                    <div class="clr"></div>                                         			
                                </div>
                                <div class="clr"></div>                               
                                <div id="row">
                                    <div class="label">Amount</div>
                                    <?php echo $amount;?>			
                                </div>
                                <div id="row">
                                    <div class="label">Data</div>
                                    <?php echo $data;?>			
                                </div>
                                <div id="row">
                                    <div class="label">Status</div>
                                    <?php echo $status;?>			
                                </div>
                                <div class="clr"></div> 
                                <div class="button">
                                    <button type="submit" class="btn btn-success">Save</button></a>
                                    <a href="<?php echo $linkindex?>"><button type="button" class="btn btn-danger">Cancer</button></a>
                                </div>             
							</div>
							
                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        
                 
                        <!-- END: 	CONTENT -->
</form>